%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Benjamin\OneDrive\Documents\GitHub\QARM_RISK\10_Industry_Portfolios_Daily.CSV
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/05/10 17:14:45

%% Initialize variables.
filename = 'C:\Users\Benjamin\OneDrive\Documents\GitHub\QARM_RISK\10_Industry_Portfolios_Daily.CSV';
startRow = 7;

%% Format for each line of text:
%   column1: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%9s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false, 'EndOfLine', '\r\n');
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'ReturnOnError', false);

%% Remove white space around all cell columns.
dataArray{1} = strtrim(dataArray{1});

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
IndustryPortfoliosDaily_2 = table(dataArray{1:end-1}, 'VariableNames', {'Thisfile'});

%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;