%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Benjamin\OneDrive\Documents\GitHub\QARM_RISK\bitstampUSD_1-min_data_2012-01-01_to_2020-04-22.csv
%
% Auto-generated by MATLAB on 23-May-2020 16:47:34

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Timestamp", "Var2", "Var3", "Var4", "Close", "Volume_BTC", "Var7", "Var8"];
opts.SelectedVariableNames = ["Timestamp", "Close", "Volume_BTC"];
opts.VariableTypes = ["double", "string", "string", "string", "double", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var7", "Var8"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var7", "Var8"], "EmptyFieldRule", "auto");

% Import the data
Bitcoin = readtable("Data\bitstampUSD_1-min_data_2012-01-01_to_2020-04-22.csv", opts);


%% Clear temporary variables
clear opts