%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Benjamin\OneDrive\Documents\GitHub\QARM_RISK\10_Industry_Portfolios_Daily.CSV
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/05/10 16:50:11

%% Initialize variables.
filename = 'C:\Users\Benjamin\OneDrive\Documents\GitHub\QARM_RISK\10_Industry_Portfolios_Daily.CSV';
startRow = 7;

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%9s%8s%8s%8s%8s%8s%8s%8s%8s%8s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false, 'EndOfLine', '\r\n');
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^[-/+]*\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
IndustryPortfoliosDaily = table;
IndustryPortfoliosDaily.Thisfile = cell2mat(raw(:, 1));
IndustryPortfoliosDaily.wascre = cell2mat(raw(:, 2));
IndustryPortfoliosDaily.atedby = cell2mat(raw(:, 3));
IndustryPortfoliosDaily.CMPT_IND = cell2mat(raw(:, 4));
IndustryPortfoliosDaily.RETS_DA = cell2mat(raw(:, 5));
IndustryPortfoliosDaily.ILYusin = cell2mat(raw(:, 6));
IndustryPortfoliosDaily.gthe20 = cell2mat(raw(:, 7));
IndustryPortfoliosDaily.CRS = cell2mat(raw(:, 8));
IndustryPortfoliosDaily.Pdataba = cell2mat(raw(:, 9));
IndustryPortfoliosDaily.se = cell2mat(raw(:, 10));
IndustryPortfoliosDaily.VarName11 = cell2mat(raw(:, 11));

%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp R;